ENABLE_DEV_MODE = False

AZURE_API_KEY_PATH = 'azure_api_key.txt'
AZURE_ENDPOINT = 'azure_endpoint.txt'
AZURE_OPENAI_MODEL = 'azure_openai_model.txt'

ENABLE_ROLE_PROMPTING = True
ENABLE_KNOWLEDGE_INJECTION = True
ENABLE_NATURAL_LANGUAGE_RESTRICTION = True
ENABLE_CHAIN_OF_THOUGHT = True
ENABLE_PROCESS_ANALYSIS = True
ENABLE_FEW_SHOTS_LEARNING = True
ENABLE_NEGATIVE_PROMPTING = True

MAX_TOKENS_FOR_ADVANC_MSG_TYPES = 4096
